FROM nginx:alpine
RUN mkdir /usr/share/nginx/html/imgz/
COPY react/c44_react/c44.html /usr/share/nginx/html/
COPY react/c44_react/imgz/* /usr/share/nginx/html/imgz/
RUN mkdir /usr/share/nginx/html/lib/
COPY react/c44_react/lib/* /usr/share/nginx/html/lib/
